<?php 
	$nom_hero = $_GET['heroName'];
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Le site dont vous êtes le héros
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body id="home">
        <main>
            <section>
                <h2>Bonjour <?php echo $nom_hero ?>, votre histoire va bientôt débuter mais il vous faut choisir une race.</h2>
                <div>
                    <form method="get" action="">
                        <div>
                            <input type="radio" id="orc" name="choice" value="orc">
                            <label for="orc">Orc</label>
                        </div>
                        <div>
                            <input type="radio" id="elfe" name="choice" value="elfe">
                            <label for="elfe">Elfe</label>
                        </div>
                        <div>
                            <input type="radio" id="humain" name="choice" value="humain">
                            <label for="humain">Humain</label>
                        </div>
                        <div>
                            <input type="radio" id="nain" name="choice" value="nain">
                            <label for="nain">Nain</label>
                        </div>
                        <div>
                            <input type="submit" value="Valider le choix" />
                        </div>
                    </form>
                </div>
            </section>
            <section>
                <section>
                    <img src="assets/img/cross-swords.png" />
                    <h1>Le site dont vous êtes le héros</h1>
                </section>
            </section>
        </main>
        <script type="application/javascript" src="assets/js/index.js"></script>
    </body>
</html>