<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Le site dont vous êtes le héros
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body id="home">
        <main>
            <section>
                <h2>Quelle vie avez vous mené jusque là ?</h2>
                <div>
                    <form method="get" action="debut_vie_orc.php">
                        <div>
                            <input type="radio" id="guerre" name="debut_vie" value="guerre">
                            <label for="guerre">Vous faites parti d'une troupe de guerriers</label>
                        </div>
                        <div>
                            <input type="radio" id="explo" name="debut_vie" value="explo">
                            <label for="explo">Vous êtes un explorateur</label>
                        </div>
                        <div>
                            <input type="radio" id="autre" name="debut_vie" value="autre">
                            <label for="autre">Vous êtes orphelin et vivez de du vol</label>
                        </div>
                        <div>
                            <input type="submit" value="Valider le choix" />
                        </div>
                    </form>
                </div>
            </section>
            <section>
                <section>
                    <img src="assets/img/cross-swords.png" />
                    <h1>Le site dont vous êtes le héros</h1>
                </section>
            </section>
        </main>
        <script type="application/javascript" src="assets/js/index.js"></script>
    </body>
</html>