<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Le site dont vous êtes le héros
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <body id="home">
        <main>
            <section>
                <h2></h2>
                <div>
                    <form method="get" action="choix_vie.phtml">
                        <div>
                            <input type="radio" id="orc" name="debut_vie" value="orc">
                            <label for="orc">Vous avez grandi sur ce continent</label>
                        </div>
                        <div>
                            <input type="radio" id="elfe" name="debut_vie" value="elfe">
                            <label for="elfe">Vous venez de très loin, de la terre d'origine des elfes</label>
                        </div>
                        <div>
                            <input type="submit" value="Valider le choix" />
                        </div>
                    </form>
                </div>
            </section>
            <section>
                <section>
                    <img src="assets/img/cross-swords.png" />
                    <h1>Le site dont vous êtes le héros</h1>
                </section>
            </section>
        </main>
        <script type="application/javascript" src="assets/js/index.js"></script>
    </body>
</html>
